sudo: required

services:
  - docker

language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -t "$DESTINATION_IMAGE_NAME" .;
    docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
    docker push "$DESTINATION_IMAGE_NAME";
    fi

  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - DESTINATION_IMAGE_NAME="eu.gcr.io/census-rm-ci/rm/census-rm-sample-loader"
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - master