sudo: required

services:
  - docker

language: python

dist: xenial
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make docker

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - master